//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.ConfigDB.Entity
{
    /// <summary>
    /// 配置项目
    /// </summary>
    [Table("ConfigFile")]
    public partial class ConfigFileEntity
    {

        /// <summary>
        /// 自增Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// AppId
        /// </summary>
        public int AppId { get; set; }

        /// <summary>
        /// 配置文件名称
        /// </summary>
        [Required]
        [StringLength(128)]
        public string FileName { get; set; }

        /// <summary>
        /// 配置文件类型 1. properties 2. xml 3. json
        /// </summary>
        public int FileType { get; set; }

        /// <summary>
        /// 配置内容
        /// </summary>
        [Required]
        public string FileContent { get; set; }

        /// <summary>
        /// 配置文件描述信息
        /// </summary>
        [Required]
        [StringLength(1024)]
        public string Description { get; set; }

        /// <summary>
        /// 数据状态 1. 有效 2. 已删除
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人邮箱前缀
        /// </summary>
        [Required]
        [StringLength(32)]
        public string CreateBy { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后修改人邮箱前缀
        /// </summary>
        [Required]
        [StringLength(32)]
        public string LastUpdateBy { get; set; }

        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}